---
title: "Homework3_EPI289"
author: "Takuto Yoshida"
date: "2023-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install package
```{r}
if (!require(readxl)) {install.packages("readxl")}
if (!require(geepack)) {install.packages("geepack")}
if (!require(sandwich)) {install.packages("sandwich")}
```

# Import Dataset
```{r}
library("readxl")
library(geepack)
library(boot)
library(sandwich)
nhefs <- read_excel("/Users/yoshidatakuto/Dropbox/HSPH/MPH-CLE/Spring/EPI289/Homework1/nhefs.xlsx")
nhefs.nmv <- nhefs[which(!is.na(nhefs$wt82)),] 
summary(nhefs.nmv$wt82)
```

# Part 1
```{r}
# eistimation of ip weights with a logistic model
## nonstabilized ip weights
fit.pd <- glm(qsmk ~ sex + race + age + I(age^2), family=binomial('logit'), data=nhefs.nmv)
summary(fit.pd)
nhefs.nmv$pd.qsmk <- predict(fit.pd, nhefs.nmv, type="response")

nhefs.nmv$w_ns <- ifelse(nhefs.nmv$qsmk ==1, 1/nhefs.nmv$pd.qsmk, 1/(1-nhefs.nmv$pd.qsmk))
summary(nhefs.nmv$w_ns)

est_ya0_ns <- weighted.mean(nhefs.nmv$wt82_71[nhefs.nmv$qsmk==0], w=nhefs.nmv$w_ns[nhefs.nmv$qsmk==0])
est_ya1_ns <- weighted.mean(nhefs.nmv$wt82_71[nhefs.nmv$qsmk==1], w=nhefs.nmv$w_ns[nhefs.nmv$qsmk==1])
est_ya1_ns - est_ya0_ns

## stabilized ip weights
fit.pn <- glm(qsmk ~ 1, family=binomial(), data=nhefs.nmv)
summary(fit.pn)
nhefs.nmv$pn.qsmk <- predict(fit.pn, nhefs.nmv, type="response")
summary(nhefs.nmv$pn.qsmk)
prop.table(table(nhefs.nmv$qsmk))

nhefs.nmv$w_s <- ifelse(nhefs.nmv$qsmk==1, nhefs.nmv$pn.qsmk/nhefs.nmv$pd.qsmk,
                        (1-nhefs.nmv$pn.qsmk)/(1-nhefs.nmv$pd.qsmk))
summary(nhefs.nmv$w_s)

est_ya0_s <- weighted.mean(nhefs.nmv$wt82_71[nhefs.nmv$qsmk==0], w=nhefs.nmv$w_s[nhefs.nmv$qsmk==0])
est_ya1_s <- weighted.mean(nhefs.nmv$wt82_71[nhefs.nmv$qsmk==1], w=nhefs.nmv$w_s[nhefs.nmv$qsmk==1])
est_ya1_s - est_ya0_s

# saturated marginal structural model, nonstabilized weights
msm.w <- geeglm(wt82_71 ~ qsmk, data=nhefs.nmv, weights=w_ns, id=seqn,
                corstr="independence")
summary(msm.w)

beta <- coef(msm.w)
SE <- coef(summary(msm.w))[,2]
lcl <- beta-qnorm(0.975)*SE 
ucl <- beta+qnorm(0.975)*SE
cbind(beta, lcl, ucl)

# saturated marginal structural model, stabilized weights
msm.sw <- geeglm(wt82_71 ~ qsmk, data=nhefs.nmv, weights=w_s, id=seqn,
                corstr="independence")
summary(msm.sw)

beta1 <- coef(msm.sw)
SE1 <- coef(summary(msm.sw))[,2]
lcl1 <- beta-qnorm(0.975)*SE1 
ucl1 <- beta+qnorm(0.975)*SE1
cbind(beta1, lcl1, ucl1)

## Another Code
msm.sw_new <- glm(wt82_71 ~ qsmk, data = nhefs.nmv, weights=w_s)

beta2 <- coef(msm.sw_new)
SE2 <- sqrt(diag(vcovHC(msm.sw_new, type="HC0")))
lcl2 <- beta-1.96*SE2 
ucl2 <- beta+1.96*SE2
cbind(beta, lcl, ucl)
```

# Part 2
```{r}
# "check" for positivity
## Question 10
table(nhefs.nmv$age[nhefs.nmv$race == 0 & nhefs.nmv$sex == 0], 
      nhefs.nmv$qsmk[nhefs.nmv$race == 0 & nhefs.nmv$sex == 0])

## Question 11
table(nhefs.nmv$age[nhefs.nmv$race == 0 & nhefs.nmv$sex == 1], 
      nhefs.nmv$qsmk[nhefs.nmv$race == 0 & nhefs.nmv$sex == 1])

```

# Part3
```{r}
# Estimating denominator of IP weights
q3.ipw.denom <- glm(qsmk ~ sex + race + age + I(age^2), data=nhefs, family=binomial("logit"))
summary(q3.ipw.denom)

# Predicting probabilities
nhefs_d <- predict(q3.ipw.denom, nhefs, type="response")

# Fitting model for numerator of IP weights
q3.ipw.num <- glm(qsmk ~ 1, data=nhefs, family=binomial(link="logit"))
summary(q3.ipw.num)

# Predicting probabilities
nhefs$predict_n <- predict(q3.ipw.num, nhefs, type="response")

nhefs$w <- ifelse(nhefs$death==1, nhefs$predict_n/nhefs_d,
                        (1-nhefs$predict_n)/(1-nhefs_d))

# MSM with unstabilized weights for odds ratio
q3.msm.or <- glm(death ~ qsmk, data=nhefs, weights=w, family=binomial(link='logit'))
summary(q3.msm.or)
exp(coef(q3.msm.or))
 
 
 
  
# Risk difference
est_ya0_ns_p3 <- weighted.mean(nhefs.nmv$death[nhefs.nmv$qsmk==0], w=nhefs.nmv$w_ns[nhefs.nmv$qsmk==0])
est_ya1_ns_p3 <- weighted.mean(nhefs.nmv$death[nhefs.nmv$qsmk==1], w=nhefs.nmv$w_ns[nhefs.nmv$qsmk==1])
est_ya1_ns_p3 - est_ya0_ns_p3
est_ya1_ns_p3/est_ya0_ns_p3 # Risk ratio

#OR
q3.msm.or_s <- glm(death ~ qsmk, data=nhefs.nmv, weights =w_s, family=quasibinomial(link='logit'))
summary(q3.msm.or_s)
exp(coef(q3.msm.or_s))

#Q16 95% confidence interval for the causal odds ratio
exp(confint(q3.msm.or_s))
```

